services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wheelz-user-service-local-volume:/var/lib/mysql
    networks:
      - user-services
      - wheelz-app

  user_api:
    build:
      context: .
      target: development
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: .env
          target: /app/.env
          action: sync+restart
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
    ports:
      - '${PORT}:${PORT}'
    networks:
      - user-services
      - wheelz-app

volumes:
  wheelz-user-service-local-volume:

networks:
  user-services:
  wheelz-app:
    external: true
