services:
  db:
    image: mysql
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wheelz-user-service-local-volume:/var/lib/mysql
    networks:
      - user-services

  app:
    build:
      dockerfile: Dockerfile
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /app/src
    #     - action: rebuild
    #       path: package.json
    ports:
      - '${PORT}:${PORT}'
    networks:
      - user-services

volumes:
  wheelz-user-service-local-volume:

networks:
  user-services:
