name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-test.yml

  build-and-push:
    needs: lint-and-test
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: runner
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          repository: xZxCORP/infra
          event-type: deploy-microservice
          client-payload: |
            {
              "microservice_name": "wheelz_user"
            }
